name: CIS
on: push
jobs:
  build:
    name: build
    runs-on: [ubuntu-latest]
    steps:
      - name: Get Code
        uses: actions/checkout@v2
      - name: Get CMake
        uses: lukka/get-cmake@latest
      - name: Build for Linux
        run: |
            mkdir build
            mkdir bin
            cd build
            cmake ..
            make
            ls
            cp ./xinglang ../bin/
            cd ..
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
           name: build of linux
           path: bin/xinglang.out
